// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace WideWorldImporters.Shared.ApiSdk.Models.WideWorldImportersService {
    #pragma warning disable CS1591
    public class PackageType : IAdditionalDataHolder, IParsable 
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The invoiceLines property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<InvoiceLine>? InvoiceLines { get; set; }
#nullable restore
#else
        public List<InvoiceLine> InvoiceLines { get; set; }
#endif
        /// <summary>The lastEditedBy property</summary>
        public int? LastEditedBy { get; set; }
        /// <summary>The lastEditedByNavigation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Person? LastEditedByNavigation { get; set; }
#nullable restore
#else
        public Person LastEditedByNavigation { get; set; }
#endif
        /// <summary>The orderLines property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<OrderLine>? OrderLines { get; set; }
#nullable restore
#else
        public List<OrderLine> OrderLines { get; set; }
#endif
        /// <summary>The packageTypeId property</summary>
        public int? PackageTypeId { get; set; }
        /// <summary>The packageTypeName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PackageTypeName { get; set; }
#nullable restore
#else
        public string PackageTypeName { get; set; }
#endif
        /// <summary>The purchaseOrderLines property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<PurchaseOrderLine>? PurchaseOrderLines { get; set; }
#nullable restore
#else
        public List<PurchaseOrderLine> PurchaseOrderLines { get; set; }
#endif
        /// <summary>The stockItemOuterPackages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<StockItem>? StockItemOuterPackages { get; set; }
#nullable restore
#else
        public List<StockItem> StockItemOuterPackages { get; set; }
#endif
        /// <summary>The stockItemUnitPackages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<StockItem>? StockItemUnitPackages { get; set; }
#nullable restore
#else
        public List<StockItem> StockItemUnitPackages { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="PackageType"/> and sets the default values.
        /// </summary>
        public PackageType()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="PackageType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static PackageType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new PackageType();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"invoiceLines", n => { InvoiceLines = n.GetCollectionOfObjectValues<InvoiceLine>(InvoiceLine.CreateFromDiscriminatorValue)?.ToList(); } },
                {"lastEditedBy", n => { LastEditedBy = n.GetIntValue(); } },
                {"lastEditedByNavigation", n => { LastEditedByNavigation = n.GetObjectValue<Person>(Person.CreateFromDiscriminatorValue); } },
                {"orderLines", n => { OrderLines = n.GetCollectionOfObjectValues<OrderLine>(OrderLine.CreateFromDiscriminatorValue)?.ToList(); } },
                {"packageTypeId", n => { PackageTypeId = n.GetIntValue(); } },
                {"packageTypeName", n => { PackageTypeName = n.GetStringValue(); } },
                {"purchaseOrderLines", n => { PurchaseOrderLines = n.GetCollectionOfObjectValues<PurchaseOrderLine>(PurchaseOrderLine.CreateFromDiscriminatorValue)?.ToList(); } },
                {"stockItemOuterPackages", n => { StockItemOuterPackages = n.GetCollectionOfObjectValues<StockItem>(StockItem.CreateFromDiscriminatorValue)?.ToList(); } },
                {"stockItemUnitPackages", n => { StockItemUnitPackages = n.GetCollectionOfObjectValues<StockItem>(StockItem.CreateFromDiscriminatorValue)?.ToList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<InvoiceLine>("invoiceLines", InvoiceLines);
            writer.WriteIntValue("lastEditedBy", LastEditedBy);
            writer.WriteObjectValue<Person>("lastEditedByNavigation", LastEditedByNavigation);
            writer.WriteCollectionOfObjectValues<OrderLine>("orderLines", OrderLines);
            writer.WriteIntValue("packageTypeId", PackageTypeId);
            writer.WriteStringValue("packageTypeName", PackageTypeName);
            writer.WriteCollectionOfObjectValues<PurchaseOrderLine>("purchaseOrderLines", PurchaseOrderLines);
            writer.WriteCollectionOfObjectValues<StockItem>("stockItemOuterPackages", StockItemOuterPackages);
            writer.WriteCollectionOfObjectValues<StockItem>("stockItemUnitPackages", StockItemUnitPackages);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
