// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace WideWorldImporters.Shared.ApiSdk.Models.Edm {
    /// <summary>Provides operations to manage the collection of StateProvince entities.</summary>
    public enum GeometryMultiPoint_type {
        [EnumMember(Value = "MultiPoint")]
        MultiPoint,
    }
}
