// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace WideWorldImporters.Shared.ApiSdk.Models.Edm
{
    /// <summary>Provides operations to manage the collection of StateProvince entities.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GeometryLineString_type
    {
        [EnumMember(Value = "LineString")]
        #pragma warning disable CS1591
        LineString,
        #pragma warning restore CS1591
    }
}
