// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace WideWorldImporters.Shared.ApiSdk.Models.Edm {
    /// <summary>Provides operations to manage the collection of Customer entities.</summary>
    public enum GeometryPoint_type {
        [EnumMember(Value = "Point")]
        Point,
    }
}
