// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using WideWorldImporters.Shared.ApiSdk.Odata.BuyingGroups;
using WideWorldImporters.Shared.ApiSdk.Odata.Cities;
using WideWorldImporters.Shared.ApiSdk.Odata.ColdRoomTemperatures;
using WideWorldImporters.Shared.ApiSdk.Odata.Colors;
using WideWorldImporters.Shared.ApiSdk.Odata.Countries;
using WideWorldImporters.Shared.ApiSdk.Odata.CustomerCategories;
using WideWorldImporters.Shared.ApiSdk.Odata.CustomerTransactions;
using WideWorldImporters.Shared.ApiSdk.Odata.Customers;
using WideWorldImporters.Shared.ApiSdk.Odata.DeliveryMethods;
using WideWorldImporters.Shared.ApiSdk.Odata.InvoiceLines;
using WideWorldImporters.Shared.ApiSdk.Odata.Invoices;
using WideWorldImporters.Shared.ApiSdk.Odata.OrderLines;
using WideWorldImporters.Shared.ApiSdk.Odata.Orders;
using WideWorldImporters.Shared.ApiSdk.Odata.PackageTypes;
using WideWorldImporters.Shared.ApiSdk.Odata.PaymentMethods;
using WideWorldImporters.Shared.ApiSdk.Odata.People;
using WideWorldImporters.Shared.ApiSdk.Odata.PurchaseOrderLines;
using WideWorldImporters.Shared.ApiSdk.Odata.PurchaseOrders;
using WideWorldImporters.Shared.ApiSdk.Odata.SpecialDeals;
using WideWorldImporters.Shared.ApiSdk.Odata.StateProvinces;
using WideWorldImporters.Shared.ApiSdk.Odata.StockGroups;
using WideWorldImporters.Shared.ApiSdk.Odata.StockItemHoldings;
using WideWorldImporters.Shared.ApiSdk.Odata.StockItemStockGroups;
using WideWorldImporters.Shared.ApiSdk.Odata.StockItemTransactions;
using WideWorldImporters.Shared.ApiSdk.Odata.StockItems;
using WideWorldImporters.Shared.ApiSdk.Odata.SupplierCategories;
using WideWorldImporters.Shared.ApiSdk.Odata.SupplierTransactions;
using WideWorldImporters.Shared.ApiSdk.Odata.Suppliers;
using WideWorldImporters.Shared.ApiSdk.Odata.SystemParameters;
using WideWorldImporters.Shared.ApiSdk.Odata.TransactionTypes;
using WideWorldImporters.Shared.ApiSdk.Odata.VehicleTemperatures;
namespace WideWorldImporters.Shared.ApiSdk.Odata
{
    /// <summary>
    /// Builds and executes requests for operations under \odata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OdataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Provides operations to manage the collection of BuyingGroup entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.BuyingGroups.BuyingGroupsRequestBuilder BuyingGroups
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.BuyingGroups.BuyingGroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of City entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.Cities.CitiesRequestBuilder Cities
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.Cities.CitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of ColdRoomTemperature entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.ColdRoomTemperatures.ColdRoomTemperaturesRequestBuilder ColdRoomTemperatures
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.ColdRoomTemperatures.ColdRoomTemperaturesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of Color entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.Colors.ColorsRequestBuilder Colors
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.Colors.ColorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of Country entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.Countries.CountriesRequestBuilder Countries
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of CustomerCategory entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.CustomerCategories.CustomerCategoriesRequestBuilder CustomerCategories
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.CustomerCategories.CustomerCategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of Customer entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.Customers.CustomersRequestBuilder Customers
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.Customers.CustomersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of CustomerTransaction entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.CustomerTransactions.CustomerTransactionsRequestBuilder CustomerTransactions
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.CustomerTransactions.CustomerTransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of DeliveryMethod entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.DeliveryMethods.DeliveryMethodsRequestBuilder DeliveryMethods
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.DeliveryMethods.DeliveryMethodsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of InvoiceLine entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.InvoiceLines.InvoiceLinesRequestBuilder InvoiceLines
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.InvoiceLines.InvoiceLinesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of Invoice entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.Invoices.InvoicesRequestBuilder Invoices
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.Invoices.InvoicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of OrderLine entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.OrderLines.OrderLinesRequestBuilder OrderLines
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.OrderLines.OrderLinesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of Order entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.Orders.OrdersRequestBuilder Orders
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of PackageType entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.PackageTypes.PackageTypesRequestBuilder PackageTypes
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.PackageTypes.PackageTypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of PaymentMethod entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.PaymentMethods.PaymentMethodsRequestBuilder PaymentMethods
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.PaymentMethods.PaymentMethodsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of Person entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.People.PeopleRequestBuilder People
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.People.PeopleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of PurchaseOrderLine entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.PurchaseOrderLines.PurchaseOrderLinesRequestBuilder PurchaseOrderLines
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.PurchaseOrderLines.PurchaseOrderLinesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of PurchaseOrder entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.PurchaseOrders.PurchaseOrdersRequestBuilder PurchaseOrders
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.PurchaseOrders.PurchaseOrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of SpecialDeal entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.SpecialDeals.SpecialDealsRequestBuilder SpecialDeals
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.SpecialDeals.SpecialDealsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of StateProvince entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.StateProvinces.StateProvincesRequestBuilder StateProvinces
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.StateProvinces.StateProvincesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of StockGroup entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.StockGroups.StockGroupsRequestBuilder StockGroups
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.StockGroups.StockGroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of StockItemHolding entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.StockItemHoldings.StockItemHoldingsRequestBuilder StockItemHoldings
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.StockItemHoldings.StockItemHoldingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of StockItem entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.StockItems.StockItemsRequestBuilder StockItems
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.StockItems.StockItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of StockItemStockGroup entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.StockItemStockGroups.StockItemStockGroupsRequestBuilder StockItemStockGroups
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.StockItemStockGroups.StockItemStockGroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of StockItemTransaction entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.StockItemTransactions.StockItemTransactionsRequestBuilder StockItemTransactions
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.StockItemTransactions.StockItemTransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of SupplierCategory entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.SupplierCategories.SupplierCategoriesRequestBuilder SupplierCategories
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.SupplierCategories.SupplierCategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of Supplier entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.Suppliers.SuppliersRequestBuilder Suppliers
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.Suppliers.SuppliersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of SupplierTransaction entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.SupplierTransactions.SupplierTransactionsRequestBuilder SupplierTransactions
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.SupplierTransactions.SupplierTransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of SystemParameter entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.SystemParameters.SystemParametersRequestBuilder SystemParameters
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.SystemParameters.SystemParametersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of TransactionType entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.TransactionTypes.TransactionTypesRequestBuilder TransactionTypes
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.TransactionTypes.TransactionTypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of VehicleTemperature entities.</summary>
        public global::WideWorldImporters.Shared.ApiSdk.Odata.VehicleTemperatures.VehicleTemperaturesRequestBuilder VehicleTemperatures
        {
            get => new global::WideWorldImporters.Shared.ApiSdk.Odata.VehicleTemperatures.VehicleTemperaturesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::WideWorldImporters.Shared.ApiSdk.Odata.OdataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OdataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/odata", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::WideWorldImporters.Shared.ApiSdk.Odata.OdataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OdataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/odata", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
