// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WideWorldImporters.Server.Database.Models;

public partial class BuyingGroup
{
    public int BuyingGroupId { get; set; }

    public string BuyingGroupName { get; set; }

    public int LastEditedBy { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual Person LastEditedByNavigation { get; set; }

    public virtual ICollection<SpecialDeal> SpecialDeals { get; set; } = new List<SpecialDeal>();
}