// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WideWorldImporters.Server.Database.Models;

public partial class PackageType
{
    public int PackageTypeId { get; set; }

    public string PackageTypeName { get; set; }

    public int LastEditedBy { get; set; }

    public virtual ICollection<InvoiceLine> InvoiceLines { get; set; } = new List<InvoiceLine>();

    public virtual Person LastEditedByNavigation { get; set; }

    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; } = new List<PurchaseOrderLine>();

    public virtual ICollection<StockItem> StockItemOuterPackages { get; set; } = new List<StockItem>();

    public virtual ICollection<StockItem> StockItemUnitPackages { get; set; } = new List<StockItem>();
}