// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace WideWorldImporters.Server.Database.Models;

public partial class StateProvince
{
    public int StateProvinceId { get; set; }

    public string StateProvinceCode { get; set; }

    public string StateProvinceName { get; set; }

    public int CountryId { get; set; }

    public string SalesTerritory { get; set; }

    public Geometry Border { get; set; }

    public long? LatestRecordedPopulation { get; set; }

    public int LastEditedBy { get; set; }

    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    public virtual Country Country { get; set; }

    public virtual Person LastEditedByNavigation { get; set; }
}